#!/usr/bin/env bash
MMPSVER=$1
[ ${#MMPSVER} -eq 0 ] && echo "MMPS Version is invalid" && exit -1
GITROOT=$2
[ ${#GITROOT} -eq 0 ] && echo "GITROOT is invalid" && exit -1
[ ! -d $GITROOT ] && echo "GITROOT does not exist" && exit -1

docker run -it --rm \
           -v /usr/pubsw/packages/MMPS/atlases:/usr/pubsw/packages/MMPS/atlases \
           -v /space/syn09/1/data/MMILDB/xfgavin/docker/MMPS/external:/usr/pubsw/packages/MMPS/external \
           -v /space/syn09/1/data/MMILDB/xfgavin/docker/MMPS/MMPS_$MMPSVER:/usr/pubsw/packages/MMPS/MMPS_$MMPSVER \
           -v /usr/pubsw/packages/MMPS/startup_MMPS.m:/usr/pubsw/packages/MMPS/startup_MMPS.m \
           -v /usr/pubsw/packages/matlab/R2014b:/usr/pubsw/packages/matlab/R2014b \
           -v /usr/pubsw/packages/spm/spm5b:/usr/pubsw/packages/spm/spm5b \
           -v $GITROOT:/mnt \
       abcd:dev /bin/tcsh
